// Secure Wi-Fi provisioning for Battery Monitor.
//
// Uses Espressif Unified Provisioning over a WPA2 SoftAP with Protocomm
// Security 2 (SRP6a + AES-256-GCM). The per-device setup code is generated by
// the password-protected Windows admin tool and written over trusted USB.
//
// Stored on the ESP32:
//   - SRP username (not secret)
//   - SRP salt + verifier (not the Security-2 plaintext password)
//   - setup code only as the WPA2 SoftAP service key
//
// The setup code itself is the user-facing credential. QR codes are only a
// convenient encoding of the same service name / username / setup code.

#include <network_provisioning/manager.h>
#include <network_provisioning/scheme_softap.h>
#include <esp_srp.h>
#include <esp_wifi.h>
#include <esp_event.h>

static const char* PROV_NAMESPACE = "batsec";
static const char* PROV_DEFAULT_USERNAME = "batmon";
static const size_t PROV_SALT_BYTES = 16;

static String provisioningUsername;
static String provisioningServiceKey;
static uint8_t* provisioningSalt = nullptr;
static size_t provisioningSaltLen = 0;
static uint8_t* provisioningVerifier = nullptr;
static size_t provisioningVerifierLen = 0;
static network_prov_security2_params_t provisioningSec2Params = {};
static bool secureProvisioningActive = false;
static bool secureProvisioningInitialized = false;
static bool secureProvisioningEventRegistered = false;
static bool secureProvisioningRebootRequested = false;
static unsigned long secureProvisioningRebootAtMs = 0;

static void freeProvisioningMaterial() {
  if (provisioningSalt) {
    free(provisioningSalt);
    provisioningSalt = nullptr;
  }
  if (provisioningVerifier) {
    free(provisioningVerifier);
    provisioningVerifier = nullptr;
  }
  provisioningSaltLen = 0;
  provisioningVerifierLen = 0;
  memset(&provisioningSec2Params, 0, sizeof(provisioningSec2Params));
}

bool loadProvisioningIdentity() {
  freeProvisioningMaterial();
  Preferences secPrefs;
  if (!secPrefs.begin(PROV_NAMESPACE, true)) return false;

  provisioningUsername = secPrefs.getString("user", "");
  provisioningServiceKey = secPrefs.getString("apkey", "");
  provisioningSaltLen = secPrefs.getBytesLength("salt");
  provisioningVerifierLen = secPrefs.getBytesLength("verifier");

  bool plausible = provisioningUsername.length() >= 1 &&
                   provisioningUsername.length() <= 32 &&
                   provisioningServiceKey.length() >= 8 &&
                   provisioningServiceKey.length() <= 63 &&
                   provisioningSaltLen >= 8 && provisioningSaltLen <= 64 &&
                   provisioningVerifierLen >= 64 && provisioningVerifierLen <= 512;

  if (!plausible) {
    secPrefs.end();
    provisioningUsername = "";
    provisioningServiceKey = "";
    provisioningSaltLen = 0;
    provisioningVerifierLen = 0;
    return false;
  }

  provisioningSalt = (uint8_t*)malloc(provisioningSaltLen);
  provisioningVerifier = (uint8_t*)malloc(provisioningVerifierLen);
  if (!provisioningSalt || !provisioningVerifier) {
    secPrefs.end();
    freeProvisioningMaterial();
    provisioningUsername = "";
    provisioningServiceKey = "";
    return false;
  }

  size_t saltRead = secPrefs.getBytes("salt", provisioningSalt, provisioningSaltLen);
  size_t verifierRead = secPrefs.getBytes("verifier", provisioningVerifier, provisioningVerifierLen);
  secPrefs.end();
  if (saltRead != provisioningSaltLen || verifierRead != provisioningVerifierLen) {
    freeProvisioningMaterial();
    provisioningUsername = "";
    provisioningServiceKey = "";
    return false;
  }

  provisioningSec2Params.salt = (const char*)provisioningSalt;
  provisioningSec2Params.salt_len = (uint16_t)provisioningSaltLen;
  provisioningSec2Params.verifier = (const char*)provisioningVerifier;
  provisioningSec2Params.verifier_len = (uint16_t)provisioningVerifierLen;
  return true;
}

bool hasProvisioningIdentity() {
  return provisioningUsername.length() > 0 &&
         provisioningServiceKey.length() >= 8 &&
         provisioningSalt && provisioningVerifier &&
         provisioningSaltLen > 0 && provisioningVerifierLen > 0;
}

String provisioningIdentitySummary() {
  if (!hasProvisioningIdentity()) return "UNSET";
  return String("READY ") + percentEncode(provisioningUsername) + " " + apSsid;
}

bool setProvisioningIdentity(const String& usernameValue, const String& setupCode, String& errorOut) {
#if !defined(CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2)
  errorOut = "SECURITY2_NOT_ENABLED";
  return false;
#else
  String username = usernameValue;
  username.trim();
  if (username.length() < 1 || username.length() > 32) {
    errorOut = "INVALID_USERNAME";
    return false;
  }
  if (setupCode.length() < 12 || setupCode.length() > 63) {
    errorOut = "INVALID_SETUP_CODE";
    return false;
  }

  char* salt = nullptr;
  char* verifier = nullptr;
  int verifierLen = 0;
  esp_err_t err = esp_srp_gen_salt_verifier(
    username.c_str(), username.length(),
    setupCode.c_str(), setupCode.length(),
    &salt, (int)PROV_SALT_BYTES,
    &verifier, &verifierLen
  );
  if (err != ESP_OK || !salt || !verifier || verifierLen <= 0) {
    if (salt) free(salt);
    if (verifier) free(verifier);
    errorOut = String("SRP_GENERATION_FAILED_") + String((int)err);
    return false;
  }

  Preferences secPrefs;
  if (!secPrefs.begin(PROV_NAMESPACE, false)) {
    free(salt);
    free(verifier);
    errorOut = "NVS_OPEN_FAILED";
    return false;
  }

  bool ok = secPrefs.putString("user", username) > 0 &&
            secPrefs.putString("apkey", setupCode) > 0 &&
            secPrefs.putBytes("salt", salt, PROV_SALT_BYTES) == PROV_SALT_BYTES &&
            secPrefs.putBytes("verifier", verifier, (size_t)verifierLen) == (size_t)verifierLen;
  secPrefs.end();
  free(salt);
  free(verifier);

  if (!ok || !loadProvisioningIdentity()) {
    errorOut = "NVS_WRITE_FAILED";
    return false;
  }

  errorOut = "";
  return true;
#endif
}

void clearProvisioningIdentity() {
  Preferences secPrefs;
  if (secPrefs.begin(PROV_NAMESPACE, false)) {
    secPrefs.clear();
    secPrefs.end();
  }
  freeProvisioningMaterial();
  provisioningUsername = "";
  provisioningServiceKey = "";
}

static void syncProvisionedWifiToBatteryMonitorPrefs() {
  wifi_config_t conf = {};
  if (esp_wifi_get_config(WIFI_IF_STA, &conf) != ESP_OK) return;
  String ssid((const char*)conf.sta.ssid);
  String password((const char*)conf.sta.password);
  if (ssid.length() > 0) saveWifiSettings(ssid, password);
}

static void secureProvisioningEventHandler(void* arg, esp_event_base_t eventBase, int32_t eventId, void* eventData) {
  if (eventBase != NETWORK_PROV_EVENT) return;
  switch (eventId) {
    case NETWORK_PROV_START:
      Serial.println("Secure provisioning started (Security 2 / WPA2 SoftAP)");
      break;
    case NETWORK_PROV_WIFI_CRED_SUCCESS:
      Serial.println("Secure provisioning Wi-Fi credentials accepted");
      syncProvisionedWifiToBatteryMonitorPrefs();
      secureProvisioningRebootRequested = true;
      secureProvisioningRebootAtMs = millis() + 1200UL;
      break;
    case NETWORK_PROV_WIFI_CRED_FAIL:
      Serial.println("Secure provisioning Wi-Fi connection failed; setup service remains available");
      break;
    case NETWORK_PROV_END:
      secureProvisioningActive = false;
      secureProvisioningInitialized = false;
      fallbackApActive = false;
      break;
    default:
      break;
  }
}

bool startSecureProvisioning() {
  if (secureProvisioningActive) return true;
  if (!hasProvisioningIdentity() && !loadProvisioningIdentity()) {
    Serial.println("Secure provisioning unavailable: no per-device setup credential. Configure by USB/admin first.");
    return false;
  }

#if !defined(CONFIG_ESP_PROTOCOMM_SUPPORT_SECURITY_VERSION_2)
  Serial.println("Secure provisioning unavailable: Arduino core was built without Security 2 support.");
  return false;
#else
  stopMdns();
  server.stop();
  discoveryUdp.stop();

  network_prov_mgr_config_t config = {};
  config.scheme = network_prov_scheme_softap;
  config.scheme_event_handler = NETWORK_PROV_EVENT_HANDLER_NONE;

  esp_err_t err = network_prov_mgr_init(config);
  if (err != ESP_OK) {
    Serial.printf("network_prov_mgr_init failed: %d\n", (int)err);
    return false;
  }
  secureProvisioningInitialized = true;

  // Re-provisioning after a router/password change is allowed, but always with
  // the same per-device setup credential unless an administrator rotates it
  // locally over USB.
  network_prov_mgr_reset_wifi_provisioning();

  if (!secureProvisioningEventRegistered) {
    err = esp_event_handler_register(NETWORK_PROV_EVENT, ESP_EVENT_ANY_ID, &secureProvisioningEventHandler, nullptr);
    if (err == ESP_OK) secureProvisioningEventRegistered = true;
  }

  err = network_prov_mgr_start_provisioning(
    NETWORK_PROV_SECURITY_2,
    (const void*)&provisioningSec2Params,
    apSsid.c_str(),
    provisioningServiceKey.c_str()
  );
  if (err != ESP_OK) {
    Serial.printf("network_prov_mgr_start_provisioning failed: %d\n", (int)err);
    network_prov_mgr_deinit();
    secureProvisioningInitialized = false;
    return false;
  }

  secureProvisioningActive = true;
  fallbackApActive = true; // API compatibility: setup AP is active.
  Serial.printf("Secure setup AP active: %s (WPA2 + Security 2)\n", apSsid.c_str());
  return true;
#endif
}

void requestStopSecureProvisioning() {
  if (!secureProvisioningInitialized) return;
  network_prov_mgr_stop_provisioning();
  fallbackApActive = false;
}

void serviceSecureProvisioning() {
  if (secureProvisioningRebootRequested && (int32_t)(millis() - secureProvisioningRebootAtMs) >= 0) {
    secureProvisioningRebootRequested = false;
    Serial.println("Secure provisioning complete; rebooting into normal Wi-Fi mode");
    Serial.flush();
    delay(100);
    ESP.restart();
  }
}
