(()=>{
  function installTractorCompletedJobs(){
    if(window.__TRACTOR_COMPLETED_JOBS_INSTALLED)return true;if(!window.TractorJobs||typeof getSessions!=='function')return false;window.__TRACTOR_COMPLETED_JOBS_INSTALLED=true;
    const style=document.createElement('style');style.textContent=`.completedItem{border-top:1px solid var(--line);padding:10px 0}.completedItem:first-child{border-top:0}.completedTitle{font-weight:800}.completedMeta{font-size:.68rem;color:var(--muted);margin-top:3px}.completedActions{display:grid;grid-template-columns:repeat(4,1fr);gap:5px;margin-top:8px}.jobSummaryGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:7px;margin:10px 0}.jobStat{border:1px solid var(--line);border-radius:9px;padding:8px}.jobStat b{display:block;font-size:.65rem;color:var(--muted)}.jobStat span{font-size:.9rem;font-weight:700}@media(max-width:520px){.completedActions{grid-template-columns:1fr 1fr}.jobSummaryGrid{grid-template-columns:1fr 1fr}}`;document.head.appendChild(style);
    const dlg=document.createElement('dialog');dlg.id='completedJobsDlg';dlg.innerHTML=`<div class="modal"><div class="statusRow"><div><h2 style="margin:0">Completed Jobs</h2><div class="small">Finished field operations. These jobs continue to protect their saved paths.</div></div><button id="completedClose">Close</button></div><div id="completedList" style="margin-top:10px"></div></div>`;document.body.appendChild(dlg);dlg.querySelector('#completedClose').onclick=()=>dlg.close();
    const sumDlg=document.createElement('dialog');sumDlg.id='jobSummaryDlg';sumDlg.innerHTML=`<div class="modal"><div class="statusRow"><h2 id="jobSummaryTitle" style="margin:0">Job Summary</h2><button id="jobSummaryClose">Close</button></div><div id="jobSummaryBody"></div></div>`;document.body.appendChild(sumDlg);sumDlg.querySelector('#jobSummaryClose').onclick=()=>sumDlg.close();
    function dur(ms){ms=Number(ms)||0;const h=Math.floor(ms/3600000),m=Math.floor(ms%3600000/60000);return h?`${h}h ${m}m`:`${m}m`}
    function dt(t){return t?new Date(t).toLocaleString():'—'}function mi(m){return Number.isFinite(Number(m))?(Number(m)/1609.344).toFixed(2)+' mi':'—'}function ac(a){return Number.isFinite(Number(a))?Number(a).toFixed(2)+' ac':'—'}function pct(v){return Number.isFinite(Number(v))?Number(v).toFixed(1)+'%':'—'}function mph(v){return Number.isFinite(Number(v))?Number(v).toFixed(1)+' mph':'—'}
    function stat(label,value){return `<div class="jobStat"><b>${escapeHTML(label)}</b><span>${escapeHTML(String(value??'—'))}</span></div>`}
    async function view(id){const rec=await window.TractorJobs.getSession(id);if(!rec)return;const s=rec.completionSummary||{};sumDlg.querySelector('#jobSummaryTitle').textContent=rec.driveName||s.pathName||'Job Summary';sumDlg.querySelector('#jobSummaryBody').innerHTML=`<div class="small">${escapeHTML([s.operation,s.pathName,s.propertyName].filter(Boolean).join(' • '))}</div><div class="jobSummaryGrid">${stat('Started',dt(s.startedAt||rec.createdAt))}${stat('Finished',dt(s.finishedAt||rec.finishedAt))}${stat('Elapsed',dur(s.elapsedMs))}${stat('Active implement',dur(s.activeWorkMs))}${stat('GPS on',dur(s.gpsOnMs))}${stat('Worked distance',mi(s.workDistanceM))}${stat('Total GPS travel',mi(s.gpsDistanceM))}${stat('Avg working speed',mph(s.avgWorkingMph))}${stat('Max GPS speed',mph(s.maxSpeedMph))}${stat('Coverage',pct(s.coveragePct))}${stat('Planned area',ac(s.plannedAcres))}${stat('Worked area',ac(s.nominalWorkedAcres))}${stat('Implement width',s.implementWidthFt?`${s.implementWidthFt} ft`:'—')}${stat('Avg GPS accuracy',s.avgAccuracyFt?`${Number(s.avgAccuracyFt).toFixed(1)} ft`:'—')}${stat('GPS/work points',s.pointCount??'—')}${stat('Reopened',rec.reopenedCount||0)}</div><div class="modalActions"><button id="jobMapView">View Map</button><button id="jobReopen" class="primary">Reopen</button><button id="jobExport">Export</button></div>`;
      sumDlg.querySelector('#jobMapView').onclick=async()=>{try{sumDlg.close();dlg.close();if(typeof loadSession!=='function')throw Error('Session loader unavailable.');await loadSession(id);if(typeof setAppMode==='function')setAppMode('drive');try{window.__TRACTOR_WORK_ACTIVE=false}catch(e){}try{updateAll?.();updateMapData?.()}catch(e){}}catch(e){alert('Could not view job map: '+(e?.message||e))}};
      sumDlg.querySelector('#jobReopen').onclick=async()=>{if(!confirm('Reopen this completed job and return it to Drive Sessions?'))return;try{await window.TractorJobs.reopen(id);sumDlg.close();dlg.close();await loadSession(id);if(typeof setAppMode==='function')setAppMode('drive');window.openTractorDriveSwitcher?.()}catch(e){alert(e?.message||e)}};
      sumDlg.querySelector('#jobExport').onclick=()=>window.TractorJobs.exportJob(id).catch(e=>alert(e?.message||e));sumDlg.showModal()}
    async function remove(id){if(!confirm('Permanently delete this completed job and all of its GPS/work history? This may allow its saved path to be deleted if no other drives use it.'))return;try{await window.TractorIntegrity.deleteDrive(id);await render();await window.TractorIntegrity.refreshPathLibrary()}catch(e){alert(e?.message||e)}}
    async function render(){const host=dlg.querySelector('#completedList');host.innerHTML='<div class="small">Loading…</div>';try{const ss=(await getSessions()).filter(s=>s.status==='completed').sort((a,b)=>(b.finishedAt||b.updatedAt||0)-(a.finishedAt||a.updatedAt||0));host.replaceChildren();if(!ss.length){host.innerHTML='<div class="small" style="padding:12px 0">No completed jobs yet.</div>';return}for(const s of ss){const c=s.completionSummary||{},r=document.createElement('div');r.className='completedItem';r.innerHTML=`<div class="completedTitle">${escapeHTML(s.driveName||s.drivePathingName||s.selectedPathingName||'Completed job')}</div><div class="completedMeta">${escapeHTML([c.operation||s?.settings?.operation,c.propertyName||s.propertyProfileName,dt(c.finishedAt||s.finishedAt)].filter(Boolean).join(' • '))}</div><div class="completedMeta">${escapeHTML(`${pct(c.coveragePct)} coverage • ${dur(c.activeWorkMs)} active • ${mi(c.workDistanceM)} worked`)}</div>`;const a=document.createElement('div');a.className='completedActions';for(const [label,fn,cls] of [['View',()=>view(s.id),'primary'],['Reopen',async()=>{await window.TractorJobs.reopen(s.id);await render();window.openTractorDriveSwitcher?.()},''],['Export',()=>window.TractorJobs.exportJob(s.id),''],['Delete',()=>remove(s.id),'danger']]){const b=document.createElement('button');b.textContent=label;b.className=cls;b.onclick=()=>Promise.resolve(fn()).catch(e=>alert(e?.message||e));a.appendChild(b)}r.appendChild(a);host.appendChild(r)}}catch(e){host.innerHTML=`<div class="small">Could not load completed jobs: ${escapeHTML(e?.message||e)}</div>`}}
    function open(){render();dlg.showModal()}
    let btn=document.getElementById('completedJobsBtn');if(!btn){btn=document.createElement('button');btn.id='completedJobsBtn';btn.textContent='Completed Jobs';const modeBar=document.querySelector('.modeBar');if(modeBar)modeBar.appendChild(btn)}btn.onclick=open;
    window.openTractorCompletedJobs=open;window.TractorCompletedJobs={open,render,view};return true
  }window.installTractorCompletedJobs=installTractorCompletedJobs;
})();