(()=>{
  function installTractorJobHistory(){
    if(window.__TRACTOR_JOB_HISTORY_INSTALLED)return true;if(typeof requireDB!=='function')return false;window.__TRACTOR_JOB_HISTORY_INSTALLED=true;
    const reqP=r=>new Promise((res,rej)=>{r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)}),txP=t=>new Promise((res,rej)=>{t.oncomplete=()=>res();t.onerror=()=>rej(t.error);t.onabort=()=>rej(t.error)}),metrics=new Map();
    const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
    async function getSession(id){if(!id)return null;const d=requireDB(),t=d.transaction('sessions','readonly');return await reqP(t.objectStore('sessions').get(id))}
    async function putSession(r){const d=requireDB(),t=d.transaction('sessions','readwrite');t.objectStore('sessions').put(r);await txP(t);return r}
    async function getPath(id){if(!id)return null;const d=requireDB(),t=d.transaction('pathings','readonly');return await reqP(t.objectStore('pathings').get(id))}
    async function pointsFor(id){const d=requireDB(),t=d.transaction('points','readonly'),i=t.objectStore('points').index('bySession'),a=await reqP(i.getAll(IDBKeyRange.only(id)));a.sort((x,y)=>num(x.seq)-num(y.seq));return a}
    function hav(a,b){if(!a||!b)return 0;const R=6371000,r=Math.PI/180,dp=(b.lat-a.lat)*r,dl=(b.lon-a.lon)*r,s=Math.sin(dp/2)**2+Math.cos(a.lat*r)*Math.cos(b.lat*r)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(s),Math.sqrt(1-s))}
    function pointDistance(pts){let d=0,last=null;for(const p of pts){if(!Number.isFinite(+p.lat)||!Number.isFinite(+p.lon))continue;if(last&&!p.breakBefore&&!p.break&&!p.segmentStart){const x=hav(last,p);if(x<250)d+=x}last=p}return d}
    function stateFor(id,rec={}){let m=metrics.get(id);if(m)return m;const j=rec.jobMetrics||{};m={gpsOnMs:num(j.gpsOnMs),gpsDistanceM:num(j.gpsDistanceM),maxSpeedMps:num(j.maxSpeedMps),accuracySumM:num(j.accuracySumM),accuracyCount:num(j.accuracyCount),lastGpsFix:null,gpsRunStartedAt:null};metrics.set(id,m);return m}
    async function persistMetrics(id){const rec=await getSession(id);if(!rec)return;const m=stateFor(id,rec);rec.jobMetrics={gpsOnMs:m.gpsOnMs+(m.gpsRunStartedAt?Date.now()-m.gpsRunStartedAt:0),gpsDistanceM:m.gpsDistanceM,maxSpeedMps:m.maxSpeedMps,accuracySumM:m.accuracySumM,accuracyCount:m.accuracyCount};rec.updatedAt=Date.now();await putSession(rec)}
    if(typeof onPosition==='function'){const orig=onPosition;onPosition=async function(pos){const sid=typeof sessionId!=='undefined'?sessionId:null;if(sid){const rec=await getSession(sid),m=stateFor(sid,rec),c=pos?.coords,p={lat:+c?.latitude,lon:+c?.longitude,time:pos?.timestamp||Date.now()};if(Number.isFinite(p.lat)&&Number.isFinite(p.lon)){if(m.lastGpsFix){const dt=(p.time-m.lastGpsFix.time)/1000,d=hav(m.lastGpsFix,p);if(dt>0&&dt<30&&d<250)m.gpsDistanceM+=d}m.lastGpsFix=p}if(Number.isFinite(c?.speed))m.maxSpeedMps=Math.max(m.maxSpeedMps,c.speed);if(Number.isFinite(c?.accuracy)){m.accuracySumM+=c.accuracy;m.accuracyCount++}}return await orig.apply(this,arguments)}}
    if(typeof startGPS==='function'){const orig=startGPS;startGPS=async function(){const r=await orig.apply(this,arguments),sid=typeof sessionId!=='undefined'?sessionId:null;if(sid&&typeof tracking!=='undefined'&&tracking){const rec=await getSession(sid),m=stateFor(sid,rec);if(!m.gpsRunStartedAt)m.gpsRunStartedAt=Date.now()}return r}}
    if(typeof stopGPS==='function'){const orig=stopGPS;stopGPS=async function(){const sid=typeof sessionId!=='undefined'?sessionId:null;if(sid){const rec=await getSession(sid),m=stateFor(sid,rec);if(m.gpsRunStartedAt){m.gpsOnMs+=Date.now()-m.gpsRunStartedAt;m.gpsRunStartedAt=null}await persistMetrics(sid).catch(()=>{})}return await orig.apply(this,arguments)}}
    function coverageFrom(rec){const p=rec?.planProgress||{},covered=p.covered&&typeof p.covered==='object'?Object.keys(p.covered).length:0,total=num(p.sampleCount||p.totalSamples||p.samplesCount,0);if(total>0)return Math.min(100,covered/total*100);if(Array.isArray(p.samples)&&p.samples.length)return Math.min(100,covered/p.samples.length*100);return null}
    function first(...v){return v.find(x=>x!==null&&x!==undefined&&x!==''&&Number.isFinite(Number(x)))??null}
    async function buildSummary(rec,finishedAt=null){
      if(!rec)return null;const pts=await pointsFor(rec.id),path=await getPath(rec.drivePathingId||rec.selectedPathingId),old=rec.completionSummary||{},m=stateFor(rec.id,rec),now=finishedAt||rec.finishedAt||Date.now(),start=rec.createdAt||rec.sessionCreatedAt||old.startedAt||now;
      const workDist=first(rec.distanceM,old.workDistanceM,pointDistance(pts))??0,activeMs=first(rec.driveElapsedMs,old.activeWorkMs)??0,gpsMs=first(rec.jobMetrics?.gpsOnMs,old.gpsOnMs,m.gpsOnMs)??0,gpsDist=first(rec.jobMetrics?.gpsDistanceM,old.gpsDistanceM,m.gpsDistanceM)??0;
      const cfg=rec.settings||{},pm=path?.planMeta||{},pc=path?.planCache||{},ps=path?.settings||{};
      const coverage=first(coverageFrom(rec),old.coveragePct);
      const plannedAcres=first(pm.activeAcres,pm.activeAreaAcres,pm.fieldAcres,path?.activeAcres,path?.fieldAcres,old.plannedAcres);
      const workedAcres=first(old.nominalWorkedAcres,workDist&&cfg.implementWidthFt?(workDist*3.280839895*cfg.implementWidthFt/43560):null);
      return {startedAt:start,finishedAt:now,elapsedMs:Math.max(0,now-start),activeWorkMs:activeMs,gpsOnMs:gpsMs,workDistanceM:workDist,gpsDistanceM:gpsDist,avgWorkingMph:activeMs>0?(workDist/1609.344)/(activeMs/3600000):0,maxSpeedMph:first(old.maxSpeedMph,(rec.jobMetrics?.maxSpeedMps??m.maxSpeedMps)*2.236936)??0,avgAccuracyFt:first(old.avgAccuracyFt,rec.jobMetrics?.accuracyCount?rec.jobMetrics.accuracySumM/rec.jobMetrics.accuracyCount*3.28084:null),coveragePct:coverage,plannedAcres,nominalWorkedAcres:workedAcres,implementWidthFt:first(cfg.implementWidthFt,ps.implementWidthFt,old.implementWidthFt),overlapFt:first(cfg.overlapFt,ps.overlapFt,old.overlapFt),pathType:cfg.pathType||ps.pathType||pm.pathType||old.pathType||null,operation:cfg.operation||old.operation||null,propertyName:rec.propertyProfileName||old.propertyName||null,pathName:rec.drivePathingName||rec.selectedPathingName||path?.name||old.pathName||null,pointCount:pts.length,plannedMiles:first(pc.miles,pm.miles,path?.miles,old.plannedMiles),reopenedCount:num(rec.reopenedCount)}
    }
    async function ensureSummary(id,persist=true){const rec=await getSession(id);if(!rec)return null;const s=await buildSummary(rec,rec.finishedAt||rec.completionSummary?.finishedAt);rec.completionSummary=s;if(persist&&rec.status==='completed'){rec.updatedAt=Date.now();await putSession(rec)}return {rec,summary:s}}
    async function finishCurrentDrive(){const sid=typeof sessionId!=='undefined'?sessionId:null;if(!sid){alert('No active drive session.');return}if(!confirm('Finish this drive and move it to Completed Jobs? You can reopen it later.'))return;try{if(typeof tracking!=='undefined'&&tracking&&typeof stopGPS==='function')await stopGPS()}catch(e){}try{window.__TRACTOR_WORK_ACTIVE=false}catch(e){}let rec=await getSession(sid);if(!rec)return;const now=Date.now();rec.status='completed';rec.finishedAt=now;rec.driveElapsedMs=num(typeof driveElapsedMs!=='undefined'?driveElapsedMs:rec.driveElapsedMs);rec.distanceM=num(typeof totalDistanceM!=='undefined'?totalDistanceM:rec.distanceM);rec.planProgress=typeof planProgress!=='undefined'?planProgress:rec.planProgress;const built=await buildSummary(rec,now);rec.completionSummary=built;rec.updatedAt=now;await putSession(rec);try{if(typeof sessionStatus!=='undefined')sessionStatus='completed'}catch(e){}localStorage.setItem('tractorActiveSessionId','');try{if(typeof setAppMode==='function')setAppMode('plan')}catch(e){}try{window.openTractorCompletedJobs?.()}catch(e){}try{window.TractorIntegrity?.refreshPathLibrary?.()}catch(e){}}
    async function reopen(id){const rec=await getSession(id);if(!rec)throw Error('Completed job not found.');if(rec.completionSummary){rec.completionHistory=Array.isArray(rec.completionHistory)?rec.completionHistory:[];rec.completionHistory.push(rec.completionSummary)}rec.status='in-progress';rec.reopenedCount=num(rec.reopenedCount)+1;rec.finishedAt=null;rec.completionSummary=null;rec.updatedAt=Date.now();await putSession(rec);return rec}
    async function exportJob(id){const rec=await getSession(id);if(!rec)throw Error('Job not found.');const pts=await pointsFor(id),payload={schema:'tractor-guidance-completed-job-v2',exportedAt:new Date().toISOString(),session:rec,points:pts},blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=((rec.driveName||'completed-job').replace(/[^a-z0-9_-]+/gi,'_'))+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
    const b=document.getElementById('finishSessionBtn');if(b)b.onclick=finishCurrentDrive;
    window.TractorJobs={getSession,putSession,pointsFor,finishCurrentDrive,reopen,exportJob,persistMetrics,buildSummary,ensureSummary};return true
  }
  window.installTractorJobHistory=installTractorJobHistory;
})();